Feat: Added json option to output json data
webtorrent/webtorrent-cli pull request #189
Opened 2021-08-06 14:12 UTC by OsmanAltun

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
added `--json` option which prints a json object containing:
 - href (base server URL)
 - argv (parsed arguments)
 - files (file names in array)

if u want specific file u can do `href/index/file_name`, make sure `file_name` is encoded
**Which issue (if any) does this pull request address?**
 - resolves #186 

**Is there anything you'd like reviewers to focus on?**
Anything I should add/remove from the JSON object?

2021-09-29 12:24 UTC, alxhotel requested changes

2021-09-29 12:24 UTC, alxhotel commented on bin/cmd.js
> +  .wrap(null)
Maybe don't wrap if `argv.json` is set to true

2021-09-29 12:24 UTC, alxhotel commented on bin/cmd.js
> +    argv.select = argv.select = (typeof argv.select === 'number')
Why is this double assignment necessary ?

2021-09-29 12:24 UTC, alxhotel commented on bin/cmd.js
> +      argv.json = argv.json = false // making sure that it prints only once
Why is this double assignment necessary ?

2021-12-07 12:02 UTC, closed without merging

2022-02-26 14:31 UTC, noctuid commented
@OsmanAltun Can you comment the reason for the double assignment? Do you have time to update this PR?